### ISSUE TITLE
点击打开或者关闭悬浮窗，什么反应也没有，不显示网速，也没有悬浮窗

### ISSUE THREAD

**Issue by Yieron** [wangjiafu5d/NetworkSpeed#1]
demo，完全不知道效果是什么，点击打开或者关闭悬浮窗，什么反应也没有，不显示网速啊，也没有悬浮窗。用的小米note。

**Comment by wangjiafu5d** [comment]
类似360在电脑上的悬浮窗。android studio编译的，在我手机上运行也没有问题，我手机是android5.1系统。不知道你的为什么不行。
应该是打开软件，右下角就会出现网速上下行数字，蓝色的；而且始终位于前端，覆盖其他软件上面；并且可以触摸拖动。
![networkspeed](https://cloud.githubusercontent.com/assets/19533761/21089614/910f0da8-c074-11e6-9262-8927f892bf77.gif)
